create table item (
                      item_id bigint generated by default as identity,
                      created_at timestamp not null,
                      updated_at timestamp not null,
                      item_detail clob not null,
                      item_name varchar(255) not null,
                      item_sell_status varchar(255),
                      price integer not null,
                      stock integer not null,
                      primary key (item_id)
)